root: results/MoWS2_fc
run_name: MoWS2_fc
seed: 123
dataset_seed: 456
append: True
# network
num_basis: 8
r_max: 4.0
l_max: 2
parity: true
num_features: 16
model_builders:
  - SimpleIrrepsConfig
  - EnergyModel
  - PerSpeciesRescale
  - RescaleEnergyEtc
  #- ForceConstantOutput
  - ForceOutput
  #- PartialForceOutput

# data set
# the keys used need to be stated at least once in key_mapping, npz_fixed_field_keys or npz_keys
# key_mapping is used to map the key in the npz file to the NequIP default values (see data/_key.py)
# all arrays are expected to have the shape of (nframe, natom, ?) except the fixed fields
# note that if your data set uses pbc, you need to also pass an array that maps to the nequip "pbc" key
dataset: ase                                                                       # type of data set, can be npz or ase
dataset_file_name: /home/akvyj/vasps/AllAtoms1.xyz                        # path to data set file
dataset_key_mapping:
  forces: forces
  energy: total_energy
  stress: stress


chemical_symbols:
  - Mo
  - S
  - W
# logging
wandb: false
# verbose: debug

# training
n_train: 1800
n_val: 200
train_val_split: sequential
batch_size: 50
validation_batch_size: 50
max_epochs: 500

# loss function
loss_coeffs: forces



# optimizer
optimizer_name: Adam